/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.PasswordUtil;
import aplicacion.TipoUsuario;
import aplicacion.Usuario;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Properties;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author alumnogreibd
 */
public class VConfiguracion extends javax.swing.JDialog {
    Usuario u;
    FachadaAplicacion fa;

    
    /**
     * Creates new form Vusuarios
     */
    public VConfiguracion(java.awt.Frame parent, boolean modal, FachadaAplicacion fa, Usuario u) {
        super(parent, modal);
        this.fa=fa;
        this.u=u;
        initComponents();
        
        UtilDateModel model = new UtilDateModel();
        model.setDate(1990, 0, 1); 
        model.setSelected(true);

        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Año");

        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

    
        panel.setLayout(new java.awt.FlowLayout()); 
        panel.add(datePicker);

        
        panel.revalidate();
        panel.repaint();

        this.datePicker = datePicker;
        IDTextField.setEditable(false);
 
        IDTextField.setText(u.getIdUsuario());
        NombreTextField.setText(u.getNombre());
        ap1TextField.setText(u.getAp1());
        ap2TextField.setText(u.getAp2());
        emailTextField.setText(u.getEmail());
        String oculto = "";
        for (int i = 0; i < 8; i++) {
        oculto += "*";
        }
        contraseñaTextField.setText(oculto);
  
        
        datePicker.getModel().setDate(
            u.getFechaNacimiento().getYear(),
            u.getFechaNacimiento().getMonthValue() - 1, 
            u.getFechaNacimiento().getDayOfMonth()
        );
        datePicker.getModel().setSelected(true);
        
        DocumentListener docListener = new DocumentListener() {
            public void changedUpdate(DocumentEvent e) { checkFields(); }
            public void removeUpdate(DocumentEvent e) { checkFields(); }
            public void insertUpdate(DocumentEvent e) { checkFields(); }
        };

        IDTextField.getDocument().addDocumentListener(docListener);
        NombreTextField.getDocument().addDocumentListener(docListener);
        ap1TextField.getDocument().addDocumentListener(docListener);
        ap2TextField.getDocument().addDocumentListener(docListener);
        emailTextField.getDocument().addDocumentListener(docListener);
        contraseñaTextField.getDocument().addDocumentListener(docListener);

        
        datePicker.getModel().addChangeListener(e -> checkFields());

        
        
    }

    
    private void checkFields() {
    boolean allFilled = !IDTextField.getText().isEmpty()
        && !NombreTextField.getText().isEmpty()
        && !ap1TextField.getText().isEmpty()
        && !ap2TextField.getText().isEmpty()
        && !emailTextField.getText().isEmpty()
        && !contraseñaTextField.getText().isEmpty()
        && datePicker.getModel().getValue() != null;

    guardarButton.setEnabled(allFilled);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        guardarButton = new javax.swing.JButton();
        eliminarCuentaButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        IDTextField = new javax.swing.JTextField();
        NombreTextField = new javax.swing.JTextField();
        ap1TextField = new javax.swing.JTextField();
        ap2TextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        contraseñaTextField = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Email:");

        jLabel5.setText("Contraseña:");

        jLabel6.setText("Fecha Nacimiento:");

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        eliminarCuentaButton.setText("Eliminar Cuenta");
        eliminarCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCuentaButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        NombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTextFieldActionPerformed(evt);
            }
        });

        ap1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap1TextFieldActionPerformed(evt);
            }
        });

        ap2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2TextFieldActionPerformed(evt);
            }
        });

        contraseñaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaTextFieldMousePressed(evt);
            }
        });
        contraseñaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(225, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ap1TextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ap2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contraseñaTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarCuentaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(salirButton)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ap1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contraseñaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarCuentaButton)
                    .addComponent(guardarButton)
                    .addComponent(salirButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
      Date selectedDate = (Date) datePicker.getModel().getValue();
      LocalDate fechaNacimiento = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

      String contrasena = contraseñaTextField.getText();

      // Si la contraseña son 8 asteriscos, no la actualizamos
      if ("********".equals(contrasena)) {
          contrasena = u.getContraseña(); // Mantener la contraseña actual
      }else{
          contrasena = PasswordUtil.hashPassword(contrasena);
      }

      // Llamamos a editarUsuario, pasando los valores de los campos excepto la contraseña si es 8 asteriscos
      fa.editarUsuario(u,
          IDTextField.getText(),
          NombreTextField.getText(),
          ap1TextField.getText(),
          ap2TextField.getText(),
          emailTextField.getText(),
          contrasena, // Aquí la contraseña solo se actualizará si no es 8 asteriscos
          fechaNacimiento,
          TipoUsuario.valueOf("Normal")
      );     

    }//GEN-LAST:event_guardarButtonActionPerformed

    

    private void eliminarCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCuentaButtonActionPerformed
        // TODO add your handling code here:
        fa.eliminarCuenta(u);
    }//GEN-LAST:event_eliminarCuentaButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void NombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTextFieldActionPerformed

    private void ap2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap2TextFieldActionPerformed

    private void ap1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap1TextFieldActionPerformed

    private void contraseñaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaTextFieldActionPerformed
        contraseñaTextField.setText("");
    }//GEN-LAST:event_contraseñaTextFieldActionPerformed

    private void contraseñaTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaTextFieldMousePressed
        // TODO add your handling code here:
         contraseñaTextField.setText("");
    }//GEN-LAST:event_contraseñaTextFieldMousePressed


    private JDatePickerImpl datePicker;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JTextField ap1TextField;
    private javax.swing.JTextField ap2TextField;
    private javax.swing.JTextField contraseñaTextField;
    private javax.swing.JButton eliminarCuentaButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
