/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Pelicula;
import aplicacion.Sesion;
import aplicacion.Usuario;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Properties;
import java.util.Calendar;
import java.util.Date;
import javax.swing.SpinnerDateModel;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DateEditor;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author alumnogreibd
 */
public class VPrincipal extends javax.swing.JFrame {

    aplicacion.FachadaAplicacion fa;
    Usuario u;
    /** Creates new form VPrincipal */
    public VPrincipal(aplicacion.FachadaAplicacion fa, Usuario u){
        this.fa=fa;
        initComponents();
        this.u=u;
        
        UtilDateModel model = new UtilDateModel();
        model.setDate(1990, 0, 1); 
        model.setSelected(true);

        Properties p = new Properties();
        p.put("text.today", "Hoy");
        p.put("text.month", "Mes");
        p.put("text.year", "Año");

        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        JDatePickerImpl datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());

    
        panel.setLayout(new java.awt.FlowLayout()); 
        panel.add(datePicker);

        
        panel.revalidate();
        panel.repaint();

        this.datePicker = datePicker;
        
        
        
        SpinnerDateModel timeModel = new SpinnerDateModel();
        timeModel.setCalendarField(Calendar.MINUTE);

        timeSpinner = new JSpinner(timeModel);
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(timeSpinner, "HH:mm");
        timeSpinner.setEditor(timeEditor);

        
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.HOUR_OF_DAY, 10);
        calendar.set(Calendar.MINUTE, 0);
        timeSpinner.setValue(calendar.getTime());

    
        panel2.setLayout(new java.awt.FlowLayout());
        panel2.add(timeSpinner);


        panel2.revalidate();
        panel2.repaint();
        
        reservarButton.setEnabled(false);
        valorarButton.setEnabled(false);
        opinionButton.setEnabled(false);
        informacionButton.setEnabled(false);
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            boolean haySeleccion = jTable1.getSelectedRow() != -1;
            reservarButton.setEnabled(haySeleccion);
            valorarButton.setEnabled(haySeleccion);
            opinionButton.setEnabled(haySeleccion);
            informacionButton.setEnabled(haySeleccion);
        });



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        peliculaTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reservarButton = new javax.swing.JButton();
        valorarButton = new javax.swing.JButton();
        opinionButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        filtrarHoraCheck = new javax.swing.JCheckBox();
        filtrarFechaCheck = new javax.swing.JCheckBox();
        informacionButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        configuracionMenuItem = new javax.swing.JMenuItem();
        comidaMenuItem = new javax.swing.JMenuItem();
        misReservasMenuItem = new javax.swing.JMenuItem();
        misValoracionesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Película:");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Hora:");

        peliculaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaTextFieldActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new ModeloTablaSesiones());
        jScrollPane1.setViewportView(jTable1);

        reservarButton.setText("Reservar");
        reservarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarButtonActionPerformed(evt);
            }
        });

        valorarButton.setText("Valorar");
        valorarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorarButtonActionPerformed(evt);
            }
        });

        opinionButton.setText("Opiniones");
        opinionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opinionButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        filtrarHoraCheck.setText("Filtrar");
        filtrarHoraCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarHoraCheckActionPerformed(evt);
            }
        });

        filtrarFechaCheck.setText("Filtrar");
        filtrarFechaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarFechaCheckActionPerformed(evt);
            }
        });

        informacionButton.setText("Información");
        informacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Menú");

        configuracionMenuItem.setText("Configuración");
        configuracionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(configuracionMenuItem);

        comidaMenuItem.setText("Comida");
        comidaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comidaMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(comidaMenuItem);

        misReservasMenuItem.setText("Mis Reservas");
        misReservasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misReservasMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(misReservasMenuItem);

        misValoracionesMenuItem.setText("Mis Valoraciones");
        misValoracionesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misValoracionesMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(misValoracionesMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reservarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opinionButton)
                                .addGap(7, 7, 7)
                                .addComponent(informacionButton)
                                .addGap(18, 18, 18)
                                .addComponent(salirButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(24, 24, 24)
                                    .addComponent(peliculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(40, 40, 40))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(filtrarFechaCheck))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(filtrarHoraCheck)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peliculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(filtrarFechaCheck)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtrarHoraCheck)
                    .addComponent(jLabel3)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservarButton)
                    .addComponent(valorarButton)
                    .addComponent(opinionButton)
                    .addComponent(salirButton)
                    .addComponent(informacionButton))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configuracionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionMenuItemActionPerformed
        // TODO add your handling code here:
        fa.configuracionUsuario(u);
    }//GEN-LAST:event_configuracionMenuItemActionPerformed

    private void peliculaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliculaTextFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        buscarSesiones();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void valorarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorarButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        Sesion sesionSeleccionada = ((ModeloTablaSesiones) jTable1.getModel()).obtenerSesion(selectedRow);
        Pelicula pelicula = fa.obtenerPelicula(sesionSeleccionada.getPelicula());

        fa.valorar(u,pelicula);
    }//GEN-LAST:event_valorarButtonActionPerformed

    private void opinionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opinionButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        Sesion sesionSeleccionada = ((ModeloTablaSesiones) jTable1.getModel()).obtenerSesion(selectedRow);
        Pelicula pelicula = fa.obtenerPelicula(sesionSeleccionada.getPelicula());

        fa.verOpiniones(pelicula);
    }//GEN-LAST:event_opinionButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        fa.salirVP();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
                                         
        ModeloTablaSesiones modelo = (ModeloTablaSesiones) jTable1.getModel();
        Sesion sesionSeleccionada = modelo.obtenerSesion(jTable1.getSelectedRow());

      
        peliculaTextField.setText(sesionSeleccionada.getPelicula());

      
        java.util.Date fecha = java.sql.Date.valueOf(sesionSeleccionada.getFecha());
        ((UtilDateModel) datePicker.getModel()).setValue(fecha);

       
        LocalTime horaInicio = sesionSeleccionada.getHoraInicio();
        LocalDate fechaHoy = LocalDate.now();
        ZonedDateTime zonedDateTime = horaInicio.atDate(fechaHoy).atZone(ZoneId.systemDefault());
        Date dateHora = Date.from(zonedDateTime.toInstant());
        timeSpinner.setValue(dateHora);


    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void filtrarHoraCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarHoraCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarHoraCheckActionPerformed

    private void filtrarFechaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarFechaCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrarFechaCheckActionPerformed

    private void reservarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        Sesion sesionSeleccionada = ((ModeloTablaSesiones) jTable1.getModel()).obtenerSesion(selectedRow);
        fa.reservar(u,sesionSeleccionada);
        
    }//GEN-LAST:event_reservarButtonActionPerformed

    private void informacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        Sesion sesionSeleccionada = ((ModeloTablaSesiones) jTable1.getModel()).obtenerSesion(selectedRow);
        Pelicula pelicula = fa.obtenerPelicula(sesionSeleccionada.getPelicula());
        
        
        fa.verInformacion(pelicula);
    }//GEN-LAST:event_informacionButtonActionPerformed

    private void misValoracionesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misValoracionesMenuItemActionPerformed
        fa.valoracionesUsuario(u);
    }//GEN-LAST:event_misValoracionesMenuItemActionPerformed

    private void misReservasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misReservasMenuItemActionPerformed
        // TODO add your handling code here:
        fa.reservasUsuario(u);
    }//GEN-LAST:event_misReservasMenuItemActionPerformed

    private void comidaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comidaMenuItemActionPerformed
        // TODO add your handling code here:
        fa.comida(u);
    }//GEN-LAST:event_comidaMenuItemActionPerformed

    private JSpinner timeSpinner;
    private JDatePickerImpl datePicker;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JMenuItem comidaMenuItem;
    private javax.swing.JMenuItem configuracionMenuItem;
    private javax.swing.JCheckBox filtrarFechaCheck;
    private javax.swing.JCheckBox filtrarHoraCheck;
    private javax.swing.JButton informacionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem misReservasMenuItem;
    private javax.swing.JMenuItem misValoracionesMenuItem;
    private javax.swing.JButton opinionButton;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField peliculaTextField;
    private javax.swing.JButton reservarButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton valorarButton;
    // End of variables declaration//GEN-END:variables

    private void buscarSesiones() {
        ModeloTablaSesiones modelo = (ModeloTablaSesiones) jTable1.getModel();

        String tituloPelicula = peliculaTextField.getText().trim();

        
        LocalDate fecha = null;
        LocalTime hora = null;

        
        if (filtrarFechaCheck.isSelected()) {
            java.util.Date selectedDate = (java.util.Date) datePicker.getModel().getValue();
            if (selectedDate != null) {
                fecha = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            }
        }

        
        if (filtrarHoraCheck.isSelected()) {
            java.util.Date selectedTime = (java.util.Date) timeSpinner.getValue();
            if (selectedTime != null) {
                hora = selectedTime.toInstant().atZone(ZoneId.systemDefault()).toLocalTime().withSecond(0).withNano(0);
            }
        }

        
        modelo.setFilas(fa.obtenerSesiones(tituloPelicula, fecha, hora));

        if (modelo.getRowCount() > 0) {
            jTable1.setRowSelectionInterval(0, 0);

            Sesion sesionSeleccionada = modelo.obtenerSesion(0);
            //peliculaTextField.setText(sesionSeleccionada.getPelicula());

           
            java.util.Date fechaSesion = java.sql.Date.valueOf(sesionSeleccionada.getFecha());
            ((UtilDateModel) datePicker.getModel()).setValue(fechaSesion);

            
            LocalTime horaInicio = sesionSeleccionada.getHoraInicio();
            ZonedDateTime zdt = horaInicio.atDate(LocalDate.now()).atZone(ZoneId.systemDefault());
            Date dateHora = Date.from(zdt.toInstant());
            timeSpinner.setValue(dateHora);
        }
    }

}
