/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Butaca;
import aplicacion.Equipo;
import aplicacion.FachadaAplicacion;
import aplicacion.Opinion;
import aplicacion.Reserva;
import aplicacion.Sesion;
import aplicacion.Usuario;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JCheckBox;

/**
 *
 * @author alumnogreibd
 */
public class VReservar extends javax.swing.JDialog {
    Usuario u;
    Sesion s;
    FachadaAplicacion fa;
    Map<Integer, JCheckBox> mapaCheckBoxes;
    int yaReservadas;

    /**
     * Creates new form VReservar
     */
    public VReservar(java.awt.Frame parent, boolean modal, FachadaAplicacion fa, Usuario u, Sesion sesionSeleccionada) {
        super(parent, modal);
        this.fa=fa;
        this.u=u;
        this.s=sesionSeleccionada;
        initComponents();
        precioTextField.setEditable(false);
        precioTextField.setText("0.0");

        
        mapaCheckBoxes = new HashMap<>();
        
        mapaCheckBoxes.put(1, b1check);
        mapaCheckBoxes.put(2, b2check);
        mapaCheckBoxes.put(3, b3check);
        mapaCheckBoxes.put(4, b4check);
        mapaCheckBoxes.put(5, b5check);
        mapaCheckBoxes.put(6, b6check);
        mapaCheckBoxes.put(7, b7check);
        mapaCheckBoxes.put(8, b8check);
        mapaCheckBoxes.put(9, b9check);
        mapaCheckBoxes.put(10, b10check);
        mapaCheckBoxes.put(11, b11check);
        mapaCheckBoxes.put(12, b12check);
        mapaCheckBoxes.put(13, b13check);
        mapaCheckBoxes.put(14, b14check);
        mapaCheckBoxes.put(15, b15check);
        mapaCheckBoxes.put(16, b16check);
        mapaCheckBoxes.put(17, b17check);
        mapaCheckBoxes.put(18, b18check);
        mapaCheckBoxes.put(19, b19check);

    
        List<Reserva> reservas = fa.obtenerReservas(s);

        

      
        for (Reserva reserva : reservas) {
            for (Butaca b : reserva.getButacas()) {
                int id = b.getIdButaca();               
                Set<Integer> claves = mapaCheckBoxes.keySet();
                for(Integer i: claves){
                    if(i==id){
                        JCheckBox cb = mapaCheckBoxes.get(id);
                        cb.setSelected(true);
                        cb.setEnabled(false);
                        yaReservadas++;
                    }
                }
            }
        }
        
        
        
        List<Equipo> equipo=fa.obtenerEquipo(s);
        
        ModeloTablaSala modelo = (ModeloTablaSala) jTable1.getModel();
       
        modelo.setFilas(equipo);
        
        nombreSalaTextField.setEditable(false);
        nombreSalaTextField.setText(equipo.get(0).getNombreSala());
        
        precioEquipoTextField.setEditable(false);
        precioEquipoTextField.setText(String.format("%.2f", calcularPrecioEquipo(equipo)));
        
    }
    
    private float calcularPrecioEquipo(List<Equipo> equipo) {
        float r=0.0f;
        for(Equipo e: equipo){
            r+=e.getPrecio();
        }
        return r;
    }
    
    private void añadirListeners() {
        for (JCheckBox checkBox : mapaCheckBoxes.values()) {
            checkBox.addActionListener(e -> actualizarPrecio());
        }
    }
    
    private void actualizarPrecio() {
        int contador = 0;
        for (JCheckBox checkBox : mapaCheckBoxes.values()) {
            if (checkBox.isSelected()) {
                contador++;
            }
        }
        double total = (contador-yaReservadas) * s.getPrecio();
        precioTextField.setText(String.format("%.2f", total));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        precioTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b1check = new javax.swing.JCheckBox();
        b4check = new javax.swing.JCheckBox();
        b2check = new javax.swing.JCheckBox();
        b3check = new javax.swing.JCheckBox();
        b5check = new javax.swing.JCheckBox();
        b7check = new javax.swing.JCheckBox();
        b8check = new javax.swing.JCheckBox();
        b9check = new javax.swing.JCheckBox();
        b10check = new javax.swing.JCheckBox();
        b11check = new javax.swing.JCheckBox();
        b6check = new javax.swing.JCheckBox();
        b12check = new javax.swing.JCheckBox();
        b13check = new javax.swing.JCheckBox();
        b14check = new javax.swing.JCheckBox();
        b15check = new javax.swing.JCheckBox();
        b16check = new javax.swing.JCheckBox();
        b17check = new javax.swing.JCheckBox();
        b18check = new javax.swing.JCheckBox();
        b19check = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        nombreSalaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        precioEquipoTextField = new javax.swing.JTextField();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        reservarButton.setText("Reservar");
        reservarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio:");

        precioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pantalla");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b1check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1checkActionPerformed(evt);
            }
        });

        b4check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4checkActionPerformed(evt);
            }
        });

        b2check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2checkActionPerformed(evt);
            }
        });

        b3check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3checkActionPerformed(evt);
            }
        });

        b5check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5checkActionPerformed(evt);
            }
        });

        b7check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7checkActionPerformed(evt);
            }
        });

        b8check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8checkActionPerformed(evt);
            }
        });

        b9check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9checkActionPerformed(evt);
            }
        });

        b10check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10checkActionPerformed(evt);
            }
        });

        b11check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11checkActionPerformed(evt);
            }
        });

        b6check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6checkActionPerformed(evt);
            }
        });

        b12check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12checkActionPerformed(evt);
            }
        });

        b13check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13checkActionPerformed(evt);
            }
        });

        b14check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14checkActionPerformed(evt);
            }
        });

        b15check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15checkActionPerformed(evt);
            }
        });

        b16check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16checkActionPerformed(evt);
            }
        });

        b17check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17checkActionPerformed(evt);
            }
        });

        b18check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18checkActionPerformed(evt);
            }
        });

        b19check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19checkActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Sala:");

        nombreSalaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreSalaTextFieldActionPerformed(evt);
            }
        });

        jTable1.setModel(new ModeloTablaSala());
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Precio Material:");

        jLabel5.setText("Equipo:");

        precioEquipoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioEquipoTextFieldActionPerformed(evt);
            }
        });

        label1.setText("Selecione las butacas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precioEquipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(precioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reservarButton)
                                .addGap(18, 18, 18)
                                .addComponent(salirButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreSalaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b6check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b2check)
                                        .addGap(4, 4, 4)
                                        .addComponent(b3check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b4check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5check))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b8check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b9check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b10check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b11check)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b12check))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b13check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b14check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b15check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b16check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b17check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b18check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b19check)))
                        .addGap(28, 28, 28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2check)
                            .addComponent(b4check)
                            .addComponent(b1check)
                            .addComponent(b3check)
                            .addComponent(b5check))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b7check)
                            .addComponent(b8check)
                            .addComponent(b9check)
                            .addComponent(b10check)
                            .addComponent(b11check)
                            .addComponent(b6check)
                            .addComponent(b12check))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b13check)
                            .addComponent(b14check)
                            .addComponent(b15check)
                            .addComponent(b16check)
                            .addComponent(b17check)
                            .addComponent(b18check)
                            .addComponent(b19check))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservarButton)
                    .addComponent(precioTextField)
                    .addComponent(jLabel1)
                    .addComponent(salirButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreSalaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precioEquipoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void reservarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarButtonActionPerformed
        // TODO add your handling code here:
        List<Integer> idsButacasSeleccionadas = new ArrayList<>();

        for (Map.Entry<Integer, JCheckBox> entry : mapaCheckBoxes.entrySet()) {
            JCheckBox cb = entry.getValue();
            if (cb.isSelected() && cb.isEnabled()) {
                idsButacasSeleccionadas.add(entry.getKey());
                System.out.println(entry.getKey());
            }
        }

        fa.reservarButacas(idsButacasSeleccionadas, s, u);

        
        this.dispose();
        
        
    }//GEN-LAST:event_reservarButtonActionPerformed

    private void b2checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b2checkActionPerformed

    private void b1checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1checkActionPerformed
        añadirListeners();
        // TODO add your handling code here:
        
    }//GEN-LAST:event_b1checkActionPerformed

    private void b3checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b3checkActionPerformed

    private void b12checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b12checkActionPerformed

    private void b17checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17checkActionPerformed
        // TODO add your handling code here:
       añadirListeners();
    }//GEN-LAST:event_b17checkActionPerformed

    private void b18checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18checkActionPerformed
        // TODO add your handling code here:
       añadirListeners();
    }//GEN-LAST:event_b18checkActionPerformed

    private void b19checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b19checkActionPerformed

    private void precioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTextFieldActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_precioTextFieldActionPerformed

    private void b4checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();;
    }//GEN-LAST:event_b4checkActionPerformed

    private void b5checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b5checkActionPerformed

    private void b6checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b6checkActionPerformed

    private void b7checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7checkActionPerformed
        // TODO add your handling code here:
       añadirListeners();
    }//GEN-LAST:event_b7checkActionPerformed

    private void b8checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b8checkActionPerformed

    private void b9checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b9checkActionPerformed

    private void b10checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b10checkActionPerformed

    private void b11checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b11checkActionPerformed

    private void b13checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13checkActionPerformed
        // TODO add your handling code here:
       añadirListeners();
    }//GEN-LAST:event_b13checkActionPerformed

    private void b14checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b14checkActionPerformed

    private void b15checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b15checkActionPerformed

    private void b16checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16checkActionPerformed
        // TODO add your handling code here:
        añadirListeners();
    }//GEN-LAST:event_b16checkActionPerformed

    private void nombreSalaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreSalaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreSalaTextFieldActionPerformed

    private void precioEquipoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioEquipoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioEquipoTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox b10check;
    private javax.swing.JCheckBox b11check;
    private javax.swing.JCheckBox b12check;
    private javax.swing.JCheckBox b13check;
    private javax.swing.JCheckBox b14check;
    private javax.swing.JCheckBox b15check;
    private javax.swing.JCheckBox b16check;
    private javax.swing.JCheckBox b17check;
    private javax.swing.JCheckBox b18check;
    private javax.swing.JCheckBox b19check;
    private javax.swing.JCheckBox b1check;
    private javax.swing.JCheckBox b2check;
    private javax.swing.JCheckBox b3check;
    private javax.swing.JCheckBox b4check;
    private javax.swing.JCheckBox b5check;
    private javax.swing.JCheckBox b6check;
    private javax.swing.JCheckBox b7check;
    private javax.swing.JCheckBox b8check;
    private javax.swing.JCheckBox b9check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private javax.swing.JTextField nombreSalaTextField;
    private javax.swing.JTextField precioEquipoTextField;
    private javax.swing.JTextField precioTextField;
    private javax.swing.JButton reservarButton;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables

    
}
